export const FoodSpecialities = [
    'Fusión',
    'Vegetariana',
    'Vegana',
    'Low carb (Keto)',
    'Saludable',
    'Gourmet',
    'Internacional',
    'Mexicana',
    'Americana',
    'Arabe',
    'Asiática',
    'Libanesa',
    'Argentina',
    'Brasileña',
    'India',
    'China',
    'Japonesa',
    'Francesa',
    'Alemana',
    'Italiana',
    'Griega',
    'Tai',
    'Española',
    'Yucateca',
    'Campechana',
    'Oaxaqueña',
    'Sushi',
    'Pasta',
    'Hamburguesas',
    'Tacos',
    'Tortas',
    'Pizzas',
    'Carnes',
    'Pescados y mariscos',
    'Helados',
    'Pasteles',
    'Panadería',
    'Alitas',
    'Sandwiches',
    'BBQ',
    'Ensaladas',
    'Crepas',
    'Carnitas',
    'Bocadillos',
    'Desayunos',
    'Repostería'
].sort();

export const regions = [
    { name: 'Aguascalientes', code: 'AS' },
    { name: 'Baja California', code: 'BC' },
    { name: 'Baja California Sur', code: 'BS' },
    { name: 'Campeche', code: 'CC' },
    { name: 'Chiapas', code: 'CS' },
    { name: 'Chihuahua', code: 'CH' },
    { name: 'Coahuila', code: 'CL' },
    { name: 'Colima', code: 'CM' },
    { name: 'Distrito Federal', code: 'DF' },
    { name: 'Durango', code: 'DG' },
    { name: 'Guanajuato', code: 'GT' },
    { name: 'Guerrero', code: 'GR' },
    { name: 'Hidalgo', code: 'HG' },
    { name: 'Jalisco', code: 'JC' },
    { name: 'México', code: 'MC' },
    { name: 'Michoacan', code: 'MN' },
    { name: 'Morelos', code: 'MS' },
    { name: 'Nayarit', code: 'NT' },
    { name: 'Nuevo León', code: 'NL' },
    { name: 'Oaxaca', code: 'OC' },
    { name: 'Puebla', code: 'PL' },
    { name: 'Querétaro', code: 'QT' },
    { name: 'Quintana Roo', code: 'QR' },
    { name: 'San Luis Potosí', code: 'SP' },
    { name: 'Sinaloa', code: 'SL' },
    { name: 'Sonora', code: 'SR' },
    { name: 'Tabasco', code: 'TC' },
    { name: 'Tlaxcala', code: 'TL' },
    { name: 'Tamaulipas', code: 'TS' },
    { name: 'Veracruz', code: 'VZ' },
    { name: 'Yucatán', code: 'YN' },
    { name: 'Zacatecas', code: 'ZS' }
];